### ISSUE TITLE
GLBoost の glTF Loader が defaultScene にしか対応していない

### ISSUE THREAD

**Issue by cx20** [emadurandal/GLBoost#101]
obj2gltf で作成した glTF ファイルが GLBoost の glTF Loader で読み込みに失敗する。

http://jsdo.it/cx20/kTDe
```
Uncaught TypeError: Cannot read property 'nodes' of undefined
    at GLTFLoader._IterateNodeOfScene (https://cdn.rawgit.com/emadurandal/GLBoost/b1ffc4106f2f7c4feb29d436a68e5c366efb7768/build/glboost.js:9460:38)
    at GLTFLoader._loadBinaryFile (https://cdn.rawgit.com/emadurandal/GLBoost/b1ffc4106f2f7c4feb29d436a68e5c366efb7768/build/glboost.js:9430:16)
    at GLTFLoader._constructMesh (https://cdn.rawgit.com/emadurandal/GLBoost/b1ffc4106f2f7c4feb29d436a68e5c366efb7768/build/glboost.js:9417:18)
    at XMLHttpRequest.xmlHttp.onreadystatechange (https://cdn.rawgit.com/emadurandal/GLBoost/b1ffc4106f2f7c4feb29d436a68e5c366efb7768/build/glboost.js:9399:21)
```

GLBoost の glTF Loader が defaultScene にしか対応していないのが原因の模様。

![image](https://cloud.githubusercontent.com/assets/1833979/19971942/ec0232ae-a223-11e6-8c8d-e8ef238d2932.png)

**Comment by emadurandal** [comment]
対応したのでクローズします。

**Comment by cx20** [comment]
最新版で 名前付き scene が読み込めることを確認。
http://jsdo.it/cx20/ocv5
